export enum PokemonTypeEnum {
    ACIER = "acier",
    COMBAT = "combat",
    DRAGON = "dragon",
    EAU = "dragon",
    ELECTRIK = "electrik",
    FEE = "fee",
    FEU = "feu",
    GLACE = "glace",
    INSECTE = "insecte",
    NORMAL = "normal",
    PLANTE = "plante",
    POISON = "poison",
    PSY = "psy",
    ROCHE = "roche",
    SOL = "sol",
    SPECTRE = "spectre",
    TENEBRES = "tenebres",
    VOL = "vol"
}
